config/routes.rb
Podweb::Application.routes.draw do
  root :to => "home#index"
  resources :users, only: [ :show, :edit, :update ]
  resources :watched_episodes, only: [ :create ]
  resources :podcasts
  get '/auth/:provider/callback' => 'sessions#create'
  get '/signin' => 'sessions#new', :as => :signin
  get '/signout' => 'sessions#destroy', :as => :signout
  get '/auth/failure' => 'sessions#failure'
end

app/models/episode.rb
class Episode < ActiveRecord::Base
  belongs_to :podcast
  has_many :watched_episodes
end

app/models/podcast.rb
class Podcast < ActiveRecord::Base
  validates_presence_of :feed_url

  before_save :save_details
  after_save :save_episodes
  after_find :update_details

  has_many :episodes
  has_and_belongs_to_many :users


  def save_details
    Feedjira::Feed.add_common_feed_element("itunes:image", :value => :href, :as => :album_art_url)

    self.raw_feed = Feedjira::Feed.fetch_raw self.feed_url
    feed = Feedjira::Feed.parse self.raw_feed

    self.album_art_url = feed.album_art_url
    self.title = feed.title
    self.description = feed.description
    self.url = feed.url
    self.updated_at = DateTime.now
  end

  def save_episodes
    Feedjira::Feed.add_common_feed_entry_element("enclosure", :value => :url, :as => :enclosure_url)
    Feedjira::Feed.add_common_feed_entry_element("itunes:image", :value => :href, :as => :image)

    feed = Feedjira::Feed.parse self.raw_feed
    feed.entries.each do |entry|
      episode = self.episodes.find_or_create_by(uid: entry.entry_id)
      episode.uid = entry.entry_id
      episode.title = entry.title
      episode.author = entry.author
      episode.link_url = entry.url
      episode.summary = entry.summary
      episode.content = entry.content
      episode.image_url = entry.image
      if defined? entry.enclosure_url
        episode.media_url = entry.enclosure_url
      elsif defined? entry.image
        episode.media_url = entry.image
      else
        episode.media_url = nil
      end
      episode.publish_date = entry.published
      episode.save
    end
  end

  def update_details
    if self.updated_at < (DateTime.now - 1.hour)
      self.save if self.raw_feed != Feedjira::Feed.fetch_raw(self.feed_url)
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :watched_episodes
  has_and_belongs_to_many :podcasts
  accepts_nested_attributes_for :podcasts

  validates_presence_of :email

  def self.create_with_omniauth(auth)
    create! do |user|
      user.provider = auth['provider']
      user.uid = auth['uid']
      if auth['info']
         user.email = auth['info']['email'] || ""
      end
    end
  end

end

app/models/watched_episode.rb
class WatchedEpisode < ActiveRecord::Base
  belongs_to :user
  belongs_to :episode
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user
  helper_method :user_signed_in?
  helper_method :correct_user?

  private
    def current_user
      begin
        @current_user ||= User.find(session[:user_id]) if session[:user_id]
      rescue Exception => e
        nil
      end
    end

    def user_signed_in?
      return true if current_user
    end

    def correct_user?
      @user = User.find(params[:id])
      unless current_user == @user
        flash[:danger] = "Access denied."
        redirect_to root_url
      end
    end

    def authenticate_user!
      if !current_user
        flash[:warning] = 'You need to sign in for access to this page.'
        redirect_to root_url
      end
    end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  require 'will_paginate/array'

  def index
    if user_signed_in?
      @episode_list = []
      current_user.podcasts.each do |podcast|
        podcast.episodes.each do |episode|
          @episode_list << episode
        end
      end

      @episode_list = @episode_list.sort_by { |episode| episode.publish_date }.reverse.paginate(page: params[:page], per_page: 10)
    end
  end
end

app/controllers/podcasts_controller.rb
class PodcastsController < ApplicationController

  require 'will_paginate/array'
  require 'feed_validator'

  before_filter :authenticate_user!, only: [ :create, :destroy ]
  before_filter :validate_podcast, only: [ :create ]

  def index
    @sort_by = params[:sort] 
    @sort_by = 'pop' unless ['a-z'].include?(@sort_by)
    if @sort_by == 'pop'
      @podcasts = Podcast.all.includes(:users).sort_by { |podcast| podcast.users.size }.reverse.paginate(page: params[:page], per_page: 12)
    else
      @podcasts = Podcast.all.sort_by { |podcast| podcast.title.sub(/^(the|a|an)\s+/i, '') }.paginate(page: params[:page], per_page: 12)
    end
    
  end

  def show
    @podcast = Podcast.find(params[:id])
    @episodes = @podcast.episodes.sort_by { |episode| episode.publish_date }.reverse.paginate(page: params[:page], per_page: 10)
  end

  def create
    podcast = Podcast.find_or_create_by(feed_url: params[:podcast][:feed_url])
    if podcast.save
      subscribe_to_podcast(podcast)
    else
      flash[:danger] = "There was an error finding or creating the Podcast."
      redirect_to current_user
    end
  end

  def destroy
    current_user.podcasts.delete(Podcast.find(params[:id]))
    redirect_to current_user
  end

  private

    def podcast_params
      params.require(:podcast).permit(:feed_url)
    end

    def validate_podcast
      begin
        v = W3C::FeedValidator.new()
        if v.validate_url(params[:podcast][:feed_url])
          feed = Feedjira::Feed.fetch_and_parse(params[:podcast][:feed_url])
          if !defined? feed.title
            flash[:danger] = "Feed has no title, probably not valid."
            redirect_to current_user
          end
        else
          flash[:danger] = "Invalid Url."
          redirect_to current_user
        end
      rescue
        flash[:danger] = "Exception caught when trying to add Podcast."
        redirect_to current_user
      end
    end

    def subscribe_to_podcast(podcast)
      if current_user.podcasts << podcast
        flash[:success] = "Successfully subscribed."
      else
        flash[:danger] = "There was an error subscribing to the Podcast."
      end
      redirect_to current_user
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    redirect_to '/auth/google_oauth2'
  end

  def create
    auth = request.env["omniauth.auth"]
    user = User.where(:provider => auth['provider'],
                      :uid => auth['uid'].to_s).first || User.create_with_omniauth(auth)
    # Reset the session after successful login, per
    # 2.8 Session Fixation – Countermeasures:
    # http://guides.rubyonrails.org/security.html#session-fixation-countermeasures
    reset_session
    session[:user_id] = user.id
    unless user.email.blank?
      flash[:success] = 'Signed in!'
      redirect_to root_url
    end

  end

  def destroy
    reset_session
    flash[:success] = 'Signed out!'
    redirect_to root_url
  end

  def failure
    flash[:danger] = "Authentication error: #{params[:message].humanize}"
    redirect_to root_url
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_filter :authenticate_user!
  before_filter :correct_user?

  def show
    @user = User.find(params[:id])
    @podcasts = @user.podcasts.sort_by { |podcast| podcast.title.sub(/^(the|a|an)\s+/i, '') }.paginate(page: params[:page], per_page: 12)
  end

end

app/controllers/watched_episodes_controller.rb
class WatchedEpisodesController < ApplicationController

  def create
    if user_signed_in?
      watched_episode = WatchedEpisode.find_or_initialize_by(user_id: current_user.id, episode_id: params[:watched_episode][:episode_id])
      watched_episode.watched = params[:watched_episode][:watched]
      watched_episode.seconds_seen = params[:watched_episode][:seconds_seen]
      watched_episode.save
    end
    render nothing: true
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  # Always use the Twitter Bootstrap pagination renderer
  def will_paginate(collection_or_options = nil, options = {})
    if collection_or_options.is_a? Hash
      options, collection_or_options = collection_or_options, nil
    end
    unless options[:renderer]
      options = options.merge :renderer => BootstrapPagination::Rails
    end
    super *[collection_or_options, options].compact
  end

end

app/views/episodes/_episode_description.html.erb
<div id="episode_description">
  <a data-toggle="modal" id="episode_summary">
    <div class="well"></div>
  </a>

  <!-- Modal -->
  <div class="modal fade" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
          <h4 class="modal-title"></h4>
        </div>
        <div class="modal-body"></div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/episodes/_episode_player.html.erb
<%= video_tag "", id: "playlist-player", controls: "controls" %>
<%= form_for WatchedEpisode.new, remote: true do |f| %>
  <%= f.hidden_field :watched, value: "false" %>
  <%= f.hidden_field :episode_id %>
  <%= f.hidden_field :seconds_seen%>
<% end %>

app/views/episodes/_episode_playlist.html.erb
<div id="media-playlist">
  <table class="table table-hover">
    <% episode_list.each do |episode| %>
      <% if user_signed_in? %>
        <% watched_episode = WatchedEpisode.find_by(user_id: current_user.id, episode_id: episode.id) %>
        <% if watched_episode %>
          <% media_element_url = "#{episode.media_url}#t=#{watched_episode.seconds_seen}" %>
          <% if watched_episode.watched %>
            <% episode_status = "" %>
          <% elsif watched_episode.seconds_seen > 0 %>
            <% episode_status = "warning" %>
          <% end %>
        <% else %>
          <% media_element_url = episode.media_url %>
          <% episode_status = "info" %>
        <% end %>
      <% else %>
        <% media_element_url = episode.media_url %>
        <% episode_status = "info" %>
      <% end %>
      <tr class="<%= episode_status %>" data-epid="<%= episode.id %>" data-mediaurl="<%= media_element_url %>" data-shortsummary="<%= truncate(strip_tags(episode.summary), length: 250) %>" data-longsummary="<%= episode.summary %>">
        <td class="text-center"><%= episode.publish_date.strftime "%a %b %d %R" %></td>
        <td class="text-center">
          <% if episode_status == "info" %>
            <span class="label label-primary">Unwatched</span>
          <% elsif episode_status == "warning" %>
            <span class="label label-warning">Watched Some</span>
          <% else %>
            <span class="label label-default">Watched</span>
          <% end %>
        </td>
        <td class="episode-title"><%= episode.title %><td>
        <td class="podcast-title"><%= episode.podcast.title %></td>
      </tr>
    <% end %>
  </table>
</div>
<div class="pagination-holder"><%= will_paginate episode_list %></div>

app/views/home/_collapse_entry.html.erb
<%
  entry = collapse_entry
  uid = entry.published.to_i
  media_file = nil
  if defined? entry.enclosure_url
    media_file = entry.enclosure_url
  elsif defined? entry.image
    media_file = entry.image
  end
%>

<div class="panel panel-default">
  <div class="panel-heading">
    <h4 class="panel-title">
      <a data-toggle="collapse" data-parent="#accordion" href="#collapse-<%= uid %>">
        <%= entry.title %>
      </a>
    </h4>
  </div>
  <div id="collapse-<%= uid %>" class="panel-collapse collapse">
    <div class="panel-body">
      <% unless media_file.blank? %>
        <% case File.extname(media_file) %>
        <% when '.mp3' %>
          <%= audio_tag media_file, id: "audio-player-#{uid}", controls: "controls" %>
        <% when '.mp4', '.m4v' %>
          <%= video_tag media_file, id: "video-player-#{uid}", preload: "metadata", controls: "controls" %>
        <% else %>
          <p class="text-center"><a href="<%= media_file %>">Media File&nbsp;(<%= File.extname(media_file) %>)</a></p>
        <% end %>
      <% end %>

      <br />
      <a data-toggle="modal" data-target="#full-entry-<%= uid %>">
        <div class="well"><%= truncate(strip_tags(entry.summary), length: 250) %></div>
      </a>
    </div>
  </div>
</div>

<!-- Modal -->
<div class="modal fade" id="full-entry-<%= uid %>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel-<%= uid %>" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="myModalLabel-<%= uid %>"><%= entry.title %></h4>
      </div>
      <div class="modal-body">
        <%= raw entry.summary %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

app/views/home/index.html.erb
<% if user_signed_in? %>
  <h1 class="text-center">Hey look, you're signed in!</h1>
  <h3 class="text-center text-muted">Here's the latest episodes from your subscribed podcasts.</h3>
  <br />
  <div class="row">
    <% if @episode_list.empty? %>
      <h2 class="text-center">No episodes :(</h2>
      <h4 class="text-center">I couldn't find any episodes for you. You should 
        <%= link_to 'subscribe to some!', podcasts_path %>
      </h4>
    <% else %>
      <%= render partial: 'episodes/episode_player' %>
      <%= render partial: 'episodes/episode_description' %>
      <%= render partial: 'episodes/episode_playlist', locals: { episode_list: @episode_list } %>
    <% end %>
  </div>
<% else %>
  <h2 class="text-center">Welcome to Podweb</h2>
  <br />
  <h4 class="text-center">Podweb is in the extremely early stages of development to become a browser-based podcast manager.</h4>
<% end %>

app/views/layouts/_footer.html.erb
<footer id="footer">
  <div class="container">
    <p class="text-muted">&copy;&nbsp;Podweb 2014</p>
  </div>
</footer>

<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-49330905-1', 'podweb.herokuapp.com');
  ga('send', 'pageview');
</script>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s %> alert-dismissable">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<header>
  <nav class="navbar navbar-inverse navbar-static-top " role="navigation">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to 'Podweb', root_path, class: 'navbar-brand' %>
      </div>
      <div class="collapse navbar-collapse">
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to 'Podcast Library', podcasts_path %></li>
          <% if user_signed_in? %>
            <li><%= link_to 'My Subscriptions', current_user %></li>
            <li><%= link_to 'Sign Out', signout_path %></li>
          <% else %>
            <li><%= link_to "", signin_path, class: "gplus-signin" %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Podweb" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Podweb" %>">
    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <%= render 'layouts/navigation' %>
    <div class="container">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/podcasts/_podcast.html.erb
<div class="podcast col-xs-6 col-sm-4 col-md-3 col-lg-2">
  <div class="thumbnail">
    <%= link_to image_tag(podcast.album_art_url), podcast %>
    <div class="caption">
      <h4 class="text-center"><%= link_to podcast.title, podcast %></h4>
      <p class="text-muted"><strong>Latest Episode</strong> <%= podcast.episodes.sort_by { |episode| episode.publish_date }.last.title %></p>
      <% if user_signed_in? %>
        <% if current_user.podcasts.include?(podcast) %>
          <%= link_to podcast, method: :delete, data: { confirm: "Unsubscribe?" } do %>
            <button type="button" class="btn btn-danger btn-block">Unsubscribe</button>
          <% end %>
        <% else %>
          <%= link_to podcasts_path(podcast: { feed_url: podcast.feed_url }), method: :post do %>
            <button type="button" class="btn btn-success btn-block">Subscribe</button>
          <% end %>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/podcasts/index.html.erb
<h3 class="text-center">Podcast Library</h3>
<br />
<% if user_signed_in? %>
  <%= render 'shared/feed_subscribe' %>
  <br />
<% end %>
<div class="row">
  <div class="col-xs-6 col-xs-offset-3">
    <h4 class="text-center">
      <%=
      case @sort_by
        when 'pop' then 'List of Popular Podcasts'
        when 'a-z' then 'Alphabetical List of Podcasts'
      end
      %>
    </h4>
  </div>
  <div class="col-xs-3">
    <span class="pull-right sort-options">
      Sort:
      <%= link_to podcasts_path(sort: 'a-z') do %>
        <span class="label label-<%= @sort_by == 'a-z' ? 'primary' : 'default' %>">A-Z</span>
      <% end %>
      <%= link_to podcasts_path(sort: 'pop') do %>
        <span class="label label-<%= @sort_by == 'pop' ? 'primary' : 'default' %>">Popular</span>
      <% end %>
    </span>
  </div>
</div>
<hr class="thin-hr" />
<div class="row">
  <%= render @podcasts %>
</div>
<div class="pagination-holder"><%= will_paginate @podcasts %></div>

app/views/podcasts/show.html.erb
<div class="row">
  <div class="col-xs-12">
    <h2 class="text-center"><%= @podcast.title %></h2>
    <br />
    <div class="row">
      <%= render partial: 'episodes/episode_player' %>
      <%= render partial: 'episodes/episode_description' %>
      <%= render partial: 'episodes/episode_playlist', locals: { episode_list: @episodes } %>
    </div>
  </div>
</div>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_feed_subscribe.html.erb
<%= form_for Podcast.new, class: "form-inline", role: "form" do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="input-group">
    <%= f.label :feed_url, class: "sr-only" %>
    <%= f.text_field :feed_url, placeholder: "Feed Url", class: "form-control" %>
    <span class="input-group-btn">
      <%= f.submit "Subscribe", class: "btn btn-default" %>
    </span>
  </div>
<% end %>

app/views/users/show.html.erb
<h3 class="text-center"><%= @user.email %></h3>
<br />
<%= render'shared/feed_subscribe' %>

<% if @podcasts.any? %>
  <h2 class="text-center">Subscriptions</h2>
  <div class="row">
    <% @podcasts.each do |podcast| %>
      <%= render podcast %>
    <% end %>
  </div>
  <div class="pagination-holder"><%= will_paginate @podcasts %></div>
<% else %>
  <h4 class="text-center">
    Looks like you haven't subscribed to any podcasts yet, just paste an rss
    link above or <%= link_to 'browse the podcast library', podcasts_path %>
    to add some to your list.
  </h4>
<% end %>